/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visitormanagement;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author jimmelbermudez7
 */
public class logs extends javax.swing.JPanel {
     Connection conn = null;   
     PreparedStatement pst = null;  
     ResultSet rs = null;

    /**
     * Creates new form logs
     */
    public logs() {
        initComponents();
        conn = databaseconn.ConnecrDb();
        Update_table();
 Core1();
    }
private void Update_table(){
        try{
           
           String sql;
            sql = "select PURPOSE,LOGINDATE,LOGINTIME from visitorreg ";
           pst=conn.prepareStatement(sql);
           
           rs = pst.executeQuery();
           tbl.setModel(DbUtils.resultSetToTableModel(rs));
          }
            catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
}
private void Update_table1(){
        try{
           
           String sql;
            sql = "select PURPOSE,LOGOUTDATE,LOGOUTTIME from visitorreg ";
           pst=conn.prepareStatement(sql);
           
           rs = pst.executeQuery();
           tbl1.setModel(DbUtils.resultSetToTableModel(rs));
          }
            catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
}
public void up(){
 try{
       String value1 = inid.getText();
       String value2 = date1.getText();
       String value3 = time1.getText();
       String value4 = ps.getText();

       String sql="update visitorreg set LOGINDATE='"+value2+"',LOGINTIME='"+value3+","+value4+"' where VID='"+value1+"'";
       pst=conn.prepareStatement(sql);
       pst.execute();
       JOptionPane.showMessageDialog(null, "Updated");
       }
        catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
        }
}
public void up1(){
 try{
       String value1 = outid.getText();
       String value2 = date1.getText();
       String value3 = time1.getText();
       String value4 = ps.getText();

       String sql="update visitorreg set LOGOUTDATE='"+value2+"',LOGOUTTIME='"+value3+","+value4+"' where VID='"+value1+"'";
       pst=conn.prepareStatement(sql);
       pst.execute();
       JOptionPane.showMessageDialog(null, "Updated");
       }
        catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
        }
}
public void Core1(){
    Thread clock= new Thread(){
    public void run(){
    for(;;){
    Calendar calen = GregorianCalendar.getInstance();
    int AM_PM = calen.get(Calendar.AM_PM);
    
     String tpattern = "hh:mm";
                    SimpleDateFormat tsdf = new SimpleDateFormat(tpattern);
                    time1.setText(tsdf.format(new java.util.Date()));
                    
    String [] days = new String [] {"","","","","","",""};
    String day_night = "";
            if (AM_PM==1)
            {day_night ="PM";}
            else
            {day_night = "AM";}
            
            ps.setText(day_night);
  //  time1.setText(hour+":"+mins+":"+secs); 



int mons = calen.get(Calendar.MONTH);
int day = calen.get(Calendar.DAY_OF_MONTH);
int yr = calen.get(Calendar.YEAR);
date1.setText(days[calen.get(Calendar.DAY_OF_WEEK)-1]+" "+(mons+1)+"/"+day+"/"+yr);    
    try {
        sleep(1000);
    } catch (InterruptedException ex) {
        
    }
} } };

clock.start();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ps = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_in = new javax.swing.JButton();
        inid = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_out = new javax.swing.JButton();
        outid = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ps.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 10, 10));

        date1.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 10, 10));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID.NO:", "LOG IN", "LOG OUT"
            }
        ));
        tbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbl);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 320, 220));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOG IN", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ID.NO:");

        btn_in.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_in.setText("LOG IN");
        btn_in.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_inMouseClicked(evt);
            }
        });
        btn_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inActionPerformed(evt);
            }
        });

        inid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inidActionPerformed(evt);
            }
        });
        inid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inidKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(86, 86, 86))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_in, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inid, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_in, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 150));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 420, 400));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOG OUT", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("ID.NO:");

        btn_out.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_out.setText("LOG OUT");
        btn_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_outMouseClicked(evt);
            }
        });
        btn_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_outActionPerformed(evt);
            }
        });

        outid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                outidKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(86, 86, 86))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(outid, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btn_out, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_out, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 150));

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID.NO:", "LOG IN", "LOG OUT"
            }
        ));
        tbl1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbl1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tbl1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 348, 220));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 440, 400));

        time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        time.setText("DATE");
        add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 140, 30));

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setText("DATE");
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 130, 30));

        time1.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        add(time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 10, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inActionPerformed
  String sql = " select LOGINDATE,LOGINTIME from visitorreg where VID=?";
  String sql2 = " select *from visitorreg where VID=? and problem='BLOCK'";      
   try {            
        pst=conn.prepareStatement(sql);           
        pst.setString(1,inid.getText());                 
        rs=pst.executeQuery();

        if(rs.next()){               
        JOptionPane.showMessageDialog(null, "WELCOME!");
        pst.execute();   
        }
        
        else{
            
        JOptionPane.showMessageDialog(null, "WRONG ID NO.","ERROR",JOptionPane.ERROR_MESSAGE);   

        inid.setText("");    
        }
   }        
   catch(Exception e){
   JOptionPane.showMessageDialog(null, e);           
   }
   
   try {            
        pst=conn.prepareStatement(sql2);           
        pst.setString(1,inid.getText());                 
        rs=pst.executeQuery();

        if(rs.next()){               
        JOptionPane.showMessageDialog(null, "YOU ARE IN BLOCKLIST!!!","ERROR",JOptionPane.ERROR_MESSAGE);
        pst.execute();   
        }
        
        else{
            
        JOptionPane.showMessageDialog(null, "WRONG ID NO.","ERROR",JOptionPane.ERROR_MESSAGE);   

        inid.setText("");    
        }
   }        
   catch(Exception e){
   JOptionPane.showMessageDialog(null, e);           
   }
        up();
        Update_table(); 
    }//GEN-LAST:event_btn_inActionPerformed

    private void tblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblAncestorAdded
Update_table();
    }//GEN-LAST:event_tblAncestorAdded

    private void btn_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_outActionPerformed
        // TODO add your handling code here:
        String sql = " select LOGOUTDATE,LOGOUTTIME from visitorreg where VID=?";
        String sql2 = " select *from visitorreg where VID=? and problem='BLOCK'";
   try {            
        pst=conn.prepareStatement(sql);           
        pst.setString(1,outid.getText());                 
        rs=pst.executeQuery();

        if(rs.next()){               
        JOptionPane.showMessageDialog(null, "WELCOME");
        pst.execute();   
        }
        else{               
        JOptionPane.showMessageDialog(null, "WRONG ID NO.","ERROR",JOptionPane.ERROR_MESSAGE);   

        outid.setText("");    
        }
   }        
   catch(Exception e){
   JOptionPane.showMessageDialog(null, e);           
   }  
   
   try {            
        pst=conn.prepareStatement(sql2);           
        pst.setString(1,inid.getText());                 
        rs=pst.executeQuery();

        if(rs.next()){               
        JOptionPane.showMessageDialog(null, "YOU ARE IN BLOCKLIST!!!","ERROR",JOptionPane.ERROR_MESSAGE);
        pst.execute();   
        }
        
        else{
            
        JOptionPane.showMessageDialog(null, "WRONG ID NO.","ERROR",JOptionPane.ERROR_MESSAGE);   

        inid.setText("");    
        }
   }        
   catch(Exception e){
   JOptionPane.showMessageDialog(null, e);           
   }
   up1();
   Update_table1();
   
    }//GEN-LAST:event_btn_outActionPerformed

    private void tbl1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbl1AncestorAdded
        // TODO add your handling code here:
        Update_table1();
        
    }//GEN-LAST:event_tbl1AncestorAdded

    private void btn_inMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inMouseClicked
        try{
            
        String sql = "insert into visitorreg (LOGINDATE,LOGINTIME)values(?,?)";
            

    pst=conn.prepareStatement(sql);
            
    pst.setString(1, date1.getText());
    pst.setString(1, time1.getText());
    
    pst.execute();  

    
      JOptionPane.showMessageDialog(null, "Saved");
      
      }
        catch(Exception e){
      JOptionPane.showMessageDialog(null, e);        
        }
    }//GEN-LAST:event_btn_inMouseClicked

    private void inidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inidActionPerformed
 
    }//GEN-LAST:event_inidActionPerformed

    private void btn_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_outMouseClicked
        // TODO add your handling code here:
         try{
            
        String sql = "insert into visitorreg (LOGOUTDATE,LOGOUTTIME)values(?,?)";
            

    pst=conn.prepareStatement(sql);
            
    pst.setString(1, date1.getText());
    pst.setString(1, time1.getText());
    
    pst.execute();  

    
      JOptionPane.showMessageDialog(null, "Saved");
      
      }
        catch(Exception e){
      JOptionPane.showMessageDialog(null, e);        
        }
    }//GEN-LAST:event_btn_outMouseClicked

    private void inidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inidKeyTyped
         char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)|| c==KeyEvent.VK_DELETE)){
        evt.consume();

} // TODO add your handling code here:
    }//GEN-LAST:event_inidKeyTyped

    private void outidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_outidKeyTyped
  char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)|| c==KeyEvent.VK_DELETE)){
        evt.consume();

}        // TODO add your handling code here:
    }//GEN-LAST:event_outidKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_in;
    private javax.swing.JButton btn_out;
    private javax.swing.JLabel date;
    private javax.swing.JLabel date1;
    private javax.swing.JTextField inid;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField outid;
    private javax.swing.JLabel ps;
    private javax.swing.JTable tbl;
    private javax.swing.JTable tbl1;
    private javax.swing.JLabel time;
    private javax.swing.JLabel time1;
    // End of variables declaration//GEN-END:variables
}
