/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visitormanagement;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author jimmelbermudez7
 */
public class registration extends javax.swing.JPanel {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null; 

    /**
     * Creates new form registration
     */
    public registration() {
        initComponents();
        conn = databaseconn.ConnecrDb();
        Update_table();
        Core1();
    }
    private void Update_table(){

        try{
           
           String sql;
            sql = "select VID,LNAME,FNAME,MI,ADDRESS,GENDER,PURPOSE,DOV from visitorreg ";
           pst=conn.prepareStatement(sql);
           
           rs = pst.executeQuery();
           tbl_visitors.setModel(DbUtils.resultSetToTableModel(rs));
          }
            catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
    }
    public void Core1(){
    Thread clock= new Thread(){
    public void run(){
    for(;;){
    Calendar calen = GregorianCalendar.getInstance();
    int AM_PM = calen.get(Calendar.AM_PM);

    

    
    String [] days = new String [] {"","","","","","",""};
    String day_night = "";
            if (AM_PM==1)
            {day_night ="PM";}
            else
            {day_night = "AM";}
            
  //  time1.setText(hour+":"+mins+":"+secs); 


    
int mons = calen.get(Calendar.MONTH);
int day = calen.get(Calendar.DAY_OF_MONTH);
int yr = calen.get(Calendar.YEAR);
date.setText(days[calen.get(Calendar.DAY_OF_WEEK)-1]+" "+(mons+1)+"/"+day+"/"+yr);    
    try {
        sleep(1000);
    } catch (InterruptedException ex) {
        
    }

} } };

clock.start();
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        date = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_visitors = new javax.swing.JTable();
        txt_purpose = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        txt_address = new javax.swing.JTextField();
        txt_mi = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setText("DATE OF VISITATION:");
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("GENDER:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 80, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("PURPOSE:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, 30));

        btn_edit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 90, 40));

        tbl_visitors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "FNAME", "LNAME", "ADDRESS", "GENDER", "PURPOSE", "DATE OF VISITATION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_visitors.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbl_visitorsAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbl_visitors);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 950, 240));

        txt_purpose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_purposeKeyTyped(evt);
            }
        });
        add(txt_purpose, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 200, 30));

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_save.setText("SAVE");
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
        });
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 90, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("DATE OF REGISTRATION:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("FEMALE");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 100, 30));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("MALE");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 90, 30));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 190, 30));

        txt_mi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_miActionPerformed(evt);
            }
        });
        txt_mi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_miKeyTyped(evt);
            }
        });
        jPanel3.add(txt_mi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 190, 30));

        txt_lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_lnameKeyTyped(evt);
            }
        });
        jPanel3.add(txt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 190, 30));

        txt_fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_fnameKeyTyped(evt);
            }
        });
        jPanel3.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 190, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("FIRST NAME:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("LAST NAME:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("MIDDLE NAME:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ADDRESS:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 30));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 360, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_miActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_miActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_miActionPerformed

    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked
        // TODO add your handling code here:
         try{
            
        String sql = "insert into visitorreg (LNAME,FNAME,MI,ADDRESS,GENDER,PURPOSE,DOV)values(?,?,?,?,?,?,?)";
            

    pst=conn.prepareStatement(sql);
                     
    pst.setString(1, txt_lname.getText());            
    pst.setString(2, txt_fname.getText());
    pst.setString(3, txt_mi.getText());           
    pst.setString(4, txt_address.getText());
    pst.setString(5, txt_GENDER);            
    pst.setString(6, txt_purpose.getText());  
    pst.setString(7, date.getText());       
    
    pst.execute();            
    txt_lname.setText("");           
    txt_fname.setText("");
    txt_mi.setText("");           
           
    txt_address.setText(""); 
    txt_purpose.setText("");
    
      JOptionPane.showMessageDialog(null, "Saved");
        
      }
        catch(Exception e){
      JOptionPane.showMessageDialog(null, e);        
        }
       Update_table();                                  
    }//GEN-LAST:event_btn_saveMouseClicked

    private void tbl_visitorsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbl_visitorsAncestorAdded
        // TODO add your handling code here:
        Update_table();
        
    }//GEN-LAST:event_tbl_visitorsAncestorAdded

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_visitors.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)tbl_visitors.getModel();
        txt_lname.setText(model.getValueAt(selectedRow, 1).toString());
        txt_fname.setText(model.getValueAt(selectedRow, 2).toString());
        txt_mi.setText(model.getValueAt(selectedRow, 3).toString());
 
        txt_address.setText(model.getValueAt(selectedRow, 4).toString());
        txt_purpose.setText(model.getValueAt(selectedRow, 6).toString());
     Update_table();   
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_saveActionPerformed

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        // TODO add your handling code here:
        txt_GENDER="M";
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
        txt_GENDER="F";
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void txt_fnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fnameKeyTyped
char c=evt.getKeyChar();
     if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
           
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fnameKeyTyped

    private void txt_lnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lnameKeyTyped
char c=evt.getKeyChar();
     if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
           
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lnameKeyTyped

    private void txt_miKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_miKeyTyped
char c=evt.getKeyChar();
     if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
           
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_miKeyTyped

    private void txt_purposeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_purposeKeyTyped
char c=evt.getKeyChar();
     if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
           
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_purposeKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_save;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_visitors;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_mi;
    private javax.swing.JTextField txt_purpose;
    // End of variables declaration//GEN-END:variables
private String txt_GENDER;



}

