/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Core1s.Myframes;

import Core1s.Myframes.MyPanels.Panel1;
import Core1s.Myframes.MyPanels.Panel2;
import Core1s.Myframes.MyPanels.Panel3;
import Core1s.Myframes.MyPanels.Panel4;
import Core1s.Myframes.MyPanels.Panel5;
import Core1s.Myframes.MyPanels.Panel6;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import legalmanagement.complaints;

/**
 *
 * @author jimmelbermudez7
 */
public class mainframe extends javax.swing.JPanel {
GridBagLayout layout=new GridBagLayout();
     Panel1 p1;
     Panel2 p2;
     Panel3 p3;
     Panel4 p4;
     Panel5 p5;
     Panel6 p6;
    /**
     * Creates new form mainframe
     */
    public mainframe() {
        initComponents();
        p1=new Panel1();
        p2=new Panel2();
        p3=new Panel3();
        p4=new Panel4();
        p5=new Panel5();
        p6=new Panel6();
        
        DynamicPanel.setLayout(layout);
        GridBagConstraints c=new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        DynamicPanel.add(p1,c);
        c.gridx=0;
        c.gridy=0;
        DynamicPanel.add(p2,c);
        c.gridx=0;
        c.gridy=0;
        DynamicPanel.add(p3,c);
        c.gridx=0;
        c.gridy=0;
        DynamicPanel.add(p4,c);
        c.gridx=0;
        c.gridy=0;
        DynamicPanel.add(p5,c);
        c.gridx=0;
        c.gridy=0;
        DynamicPanel.add(p6,c);
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelButton = new javax.swing.JPanel();
        btnPanel2 = new javax.swing.JButton();
        btnPanel3 = new javax.swing.JButton();
        btnPanel1 = new javax.swing.JButton();
        btnPanel4 = new javax.swing.JButton();
        btnPanel5 = new javax.swing.JButton();
        btnPanel6 = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelButton.setBackground(new java.awt.Color(153, 255, 153));
        PanelButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPanel2.setBackground(new java.awt.Color(255, 255, 255));
        btnPanel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPanel2.setForeground(new java.awt.Color(0, 102, 0));
        btnPanel2.setText("DOCUMENT MANAGEMENT");
        btnPanel2.setToolTipText("");
        btnPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        btnPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel2ActionPerformed(evt);
            }
        });
        PanelButton.add(btnPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 230, 48));

        btnPanel3.setBackground(new java.awt.Color(255, 255, 255));
        btnPanel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPanel3.setForeground(new java.awt.Color(0, 102, 0));
        btnPanel3.setText("FACILITY RESERVATION");
        btnPanel3.setToolTipText("");
        btnPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        btnPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel3ActionPerformed(evt);
            }
        });
        PanelButton.add(btnPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 230, 48));

        btnPanel1.setBackground(new java.awt.Color(255, 255, 255));
        btnPanel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPanel1.setForeground(new java.awt.Color(0, 102, 0));
        btnPanel1.setText("LEGAL MANAGEMENT");
        btnPanel1.setToolTipText("");
        btnPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        btnPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel1ActionPerformed(evt);
            }
        });
        PanelButton.add(btnPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 48));

        btnPanel4.setBackground(new java.awt.Color(255, 255, 255));
        btnPanel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPanel4.setForeground(new java.awt.Color(0, 102, 0));
        btnPanel4.setText("VISITOR MANAGEMENT");
        btnPanel4.setToolTipText("");
        btnPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        btnPanel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel4ActionPerformed(evt);
            }
        });
        PanelButton.add(btnPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 230, 48));

        btnPanel5.setBackground(new java.awt.Color(255, 255, 255));
        btnPanel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPanel5.setForeground(new java.awt.Color(0, 102, 0));
        btnPanel5.setText("POINT OF SALE");
        btnPanel5.setToolTipText("");
        btnPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        btnPanel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel5ActionPerformed(evt);
            }
        });
        PanelButton.add(btnPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 230, 48));

        btnPanel6.setBackground(new java.awt.Color(255, 255, 255));
        btnPanel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPanel6.setForeground(new java.awt.Color(0, 102, 0));
        btnPanel6.setText("AUDIT TRAIL");
        btnPanel6.setToolTipText("");
        btnPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        btnPanel6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel6ActionPerformed(evt);
            }
        });
        PanelButton.add(btnPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 230, 48));

        add(PanelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 430));

        DynamicPanel.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 950, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel2ActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
    }//GEN-LAST:event_btnPanel2ActionPerformed

    private void btnPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel3ActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
    }//GEN-LAST:event_btnPanel3ActionPerformed

    private void btnPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel1ActionPerformed
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
    }//GEN-LAST:event_btnPanel1ActionPerformed

    private void btnPanel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel4ActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        p5.setVisible(false);
        p6.setVisible(false);
    }//GEN-LAST:event_btnPanel4ActionPerformed

    private void btnPanel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel5ActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(true);
        p6.setVisible(false);
    }//GEN-LAST:event_btnPanel5ActionPerformed

    private void btnPanel6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel6ActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(true);
    }//GEN-LAST:event_btnPanel6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JPanel PanelButton;
    private javax.swing.JButton btnPanel1;
    private javax.swing.JButton btnPanel2;
    private javax.swing.JButton btnPanel3;
    private javax.swing.JButton btnPanel4;
    private javax.swing.JButton btnPanel5;
    private javax.swing.JButton btnPanel6;
    // End of variables declaration//GEN-END:variables
}
