/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Core1s.Myframes.MyPanels;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import legalmanagement.legalcases;
import legalmanagement.legaldocument1;
import legalmanagement.reports;
import legalmanagement.complaints;
/**
 *
 * @author BALBOA
 */
public class Panel1 extends javax.swing.JPanel {
GridBagLayout layout=new GridBagLayout();
     complaints d1;
     legalcases d2;
     legaldocument1 d3;
     reports d4;

    /**
     * Creates new form Panel1
     */
    public Panel1() {
        initComponents();
        d1=new complaints();
        d2=new legalcases();
        d3=new legaldocument1();
        d4=new reports();
        
        DynamicPanel1.setLayout(layout);
        GridBagConstraints c=new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        DynamicPanel1.add(d1,c);
        c.gridx=0;
        c.gridy=0;
        DynamicPanel1.add(d2,c);
        c.gridx=0;
        c.gridy=0;
        DynamicPanel1.add(d3,c);
        c.gridx=0;
        c.gridy=0;
        DynamicPanel1.add(d4,c);
        d1.setVisible(false);
        d2.setVisible(false);
        d3.setVisible(false);
        d4.setVisible(false);

  
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        btnlcomplains = new javax.swing.JButton();
        btnllegalcases = new javax.swing.JButton();
        btnllegaldocument = new javax.swing.JButton();
        btnlreports = new javax.swing.JButton();
        DynamicPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel.setBackground(new java.awt.Color(153, 255, 153));
        jpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlcomplains.setBackground(new java.awt.Color(255, 255, 255));
        btnlcomplains.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlcomplains.setForeground(new java.awt.Color(0, 102, 0));
        btnlcomplains.setText("COMPLAINTS");
        btnlcomplains.setToolTipText("");
        btnlcomplains.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        btnlcomplains.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlcomplainsActionPerformed(evt);
            }
        });
        jpanel.add(btnlcomplains, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 161, 29));

        btnllegalcases.setBackground(new java.awt.Color(255, 255, 255));
        btnllegalcases.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnllegalcases.setForeground(new java.awt.Color(0, 102, 0));
        btnllegalcases.setText("LEGAL CASES");
        btnllegalcases.setToolTipText("");
        btnllegalcases.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        btnllegalcases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnllegalcasesActionPerformed(evt);
            }
        });
        jpanel.add(btnllegalcases, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 161, 29));

        btnllegaldocument.setBackground(new java.awt.Color(255, 255, 255));
        btnllegaldocument.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnllegaldocument.setForeground(new java.awt.Color(0, 102, 0));
        btnllegaldocument.setText("LEGAL DOCUMENTS");
        btnllegaldocument.setToolTipText("");
        btnllegaldocument.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        btnllegaldocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnllegaldocumentActionPerformed(evt);
            }
        });
        jpanel.add(btnllegaldocument, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 161, 29));

        btnlreports.setBackground(new java.awt.Color(255, 255, 255));
        btnlreports.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlreports.setForeground(new java.awt.Color(0, 102, 0));
        btnlreports.setText("REPORTS");
        btnlreports.setToolTipText("");
        btnlreports.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        btnlreports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlreportsActionPerformed(evt);
            }
        });
        jpanel.add(btnlreports, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 161, 29));

        DynamicPanel1.setBackground(new java.awt.Color(153, 255, 153));
        DynamicPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpanel.add(DynamicPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 950, 400));

        add(jpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void btnlreportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlreportsActionPerformed
        // TODO add your handling code here:
        d1.setVisible(false);
        d2.setVisible(false);
        d3.setVisible(false);
        d4.setVisible(true);
    }//GEN-LAST:event_btnlreportsActionPerformed

    private void btnllegaldocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnllegaldocumentActionPerformed
        // TODO add your handling code here:
        d1.setVisible(false);
        d2.setVisible(false);
        d3.setVisible(true);
        d4.setVisible(false);
    }//GEN-LAST:event_btnllegaldocumentActionPerformed

    private void btnllegalcasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnllegalcasesActionPerformed
        // TODO add your handling code here:
        d1.setVisible(false);
        d2.setVisible(true);
        d3.setVisible(false);
        d4.setVisible(false);
    }//GEN-LAST:event_btnllegalcasesActionPerformed

    private void btnlcomplainsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlcomplainsActionPerformed
        // TODO add your handling code here:

        d1.setVisible(true);
        d2.setVisible(false);
        d3.setVisible(false);
        d4.setVisible(false);
    }//GEN-LAST:event_btnlcomplainsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel1;
    private javax.swing.JButton btnlcomplains;
    private javax.swing.JButton btnllegalcases;
    private javax.swing.JButton btnllegaldocument;
    private javax.swing.JButton btnlreports;
    private javax.swing.JPanel jpanel;
    // End of variables declaration//GEN-END:variables
}
