/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Core1s.Myframes.MyPanels;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import visitormanagement.reports;
import visitormanagement.logs;
import visitormanagement.registration;
import visitormanagement.request;

/**
 *
 * @author jimmelbermudez7
 */
public class Panel4 extends javax.swing.JPanel {
GridBagLayout layout=new GridBagLayout();
     registration a1;
     logs a2;
     request a3;
     reports a4;
    /**
     * Creates new form Panel4
     */
    public Panel4() {
        initComponents();
        a1=new registration();
        a2=new logs();
        a3=new request();
        a4=new reports();
        
        DynamicPanel4.setLayout(layout);
        GridBagConstraints c=new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        DynamicPanel4.add(a1,c);
        c.gridx=0;
        c.gridy=0;
        DynamicPanel4.add(a2,c);
        c.gridx=0;
        c.gridy=0;
        DynamicPanel4.add(a3,c);
        c.gridx=0;
        c.gridy=0;
        DynamicPanel4.add(a4,c);
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DynamicPanel4 = new javax.swing.JPanel();
        btnvreports = new javax.swing.JButton();
        btnvlogs = new javax.swing.JButton();
        btnvrequest = new javax.swing.JButton();
        btnrregistration = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DynamicPanel4.setBackground(new java.awt.Color(153, 255, 153));
        DynamicPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(DynamicPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 950, 400));

        btnvreports.setBackground(new java.awt.Color(255, 255, 255));
        btnvreports.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnvreports.setForeground(new java.awt.Color(0, 102, 0));
        btnvreports.setText("REPORTS");
        btnvreports.setToolTipText("");
        btnvreports.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        btnvreports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvreportsActionPerformed(evt);
            }
        });
        add(btnvreports, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 161, 29));

        btnvlogs.setBackground(new java.awt.Color(255, 255, 255));
        btnvlogs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnvlogs.setForeground(new java.awt.Color(0, 102, 0));
        btnvlogs.setText("LOGS");
        btnvlogs.setToolTipText("");
        btnvlogs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        btnvlogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvlogsActionPerformed(evt);
            }
        });
        add(btnvlogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 160, 29));

        btnvrequest.setBackground(new java.awt.Color(255, 255, 255));
        btnvrequest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnvrequest.setForeground(new java.awt.Color(0, 102, 0));
        btnvrequest.setText("V.REQUEST");
        btnvrequest.setToolTipText("");
        btnvrequest.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        btnvrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvrequestActionPerformed(evt);
            }
        });
        add(btnvrequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 160, 29));

        btnrregistration.setBackground(new java.awt.Color(255, 255, 255));
        btnrregistration.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnrregistration.setForeground(new java.awt.Color(0, 102, 0));
        btnrregistration.setText("V.REGISTRATION");
        btnrregistration.setToolTipText("");
        btnrregistration.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        btnrregistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrregistrationActionPerformed(evt);
            }
        });
        add(btnrregistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 160, 29));
    }// </editor-fold>//GEN-END:initComponents

    private void btnvlogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvlogsActionPerformed
        // TODO add your handling code here:

        a1.setVisible(false);
        a2.setVisible(true);
        a3.setVisible(false);
        a4.setVisible(false);
    }//GEN-LAST:event_btnvlogsActionPerformed

    private void btnrregistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrregistrationActionPerformed
        // TODO add your handling code here:
        a1.setVisible(true);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
    }//GEN-LAST:event_btnrregistrationActionPerformed

    private void btnvrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvrequestActionPerformed
        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(true);
        a4.setVisible(false);
    }//GEN-LAST:event_btnvrequestActionPerformed

    private void btnvreportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvreportsActionPerformed
        // TODO add your handling code here:
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(true);
    }//GEN-LAST:event_btnvreportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel4;
    private javax.swing.JButton btnrregistration;
    private javax.swing.JButton btnvlogs;
    private javax.swing.JButton btnvreports;
    private javax.swing.JButton btnvrequest;
    // End of variables declaration//GEN-END:variables
}
