/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Core1s.Myframes.MyPanels;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import pointofsale.bankdeposit;
import pointofsale.reports;

/**
 *
 * @author jimmelbermudez7
 */
public class Panel5 extends javax.swing.JPanel {
GridBagLayout layout=new GridBagLayout();
     
     bankdeposit b3;
     reports b4;
    /**
     * Creates new form Panel5
     */
    public Panel5() {
        initComponents();
       
        b3=new bankdeposit();
        b4=new reports();
        
        DynamicPanel5.setLayout(layout);
        GridBagConstraints c=new GridBagConstraints();
       
        c.gridx=0;
        c.gridy=0;
        DynamicPanel5.add(b3,c);
        c.gridx=0;
        c.gridy=0;
        DynamicPanel5.add(b4,c);

        b3.setVisible(false);
        b4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DynamicPanel5 = new javax.swing.JPanel();
        btnbank = new javax.swing.JButton();
        btnpreports = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DynamicPanel5.setBackground(new java.awt.Color(153, 255, 153));
        DynamicPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(DynamicPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 950, 400));

        btnbank.setBackground(new java.awt.Color(255, 255, 255));
        btnbank.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbank.setForeground(new java.awt.Color(0, 102, 0));
        btnbank.setText("DEPOSIT");
        btnbank.setToolTipText("");
        btnbank.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        btnbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbankActionPerformed(evt);
            }
        });
        add(btnbank, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 160, 29));

        btnpreports.setBackground(new java.awt.Color(255, 255, 255));
        btnpreports.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnpreports.setForeground(new java.awt.Color(0, 102, 0));
        btnpreports.setText("REPORTS");
        btnpreports.setToolTipText("");
        btnpreports.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        btnpreports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreportsActionPerformed(evt);
            }
        });
        add(btnpreports, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 161, 29));
    }// </editor-fold>//GEN-END:initComponents

    private void btnbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbankActionPerformed
        // TODO add your handling code here:

        b3.setVisible(true);
        b4.setVisible(false);
    }//GEN-LAST:event_btnbankActionPerformed

    private void btnpreportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreportsActionPerformed
        // TODO add your handling code here:
        b3.setVisible(false);
        b4.setVisible(true);
    }//GEN-LAST:event_btnpreportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel5;
    private javax.swing.JButton btnbank;
    private javax.swing.JButton btnpreports;
    // End of variables declaration//GEN-END:variables
}
