/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Core1s.Myframes.MyPanels;

import documentmanagement.deployment;
import documentmanagement.documents;
import documentmanagement.request;
import documentmanagement.reports;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;


/**
 *
 * @author BALBOA
 */
public class Panel2 extends javax.swing.JPanel {
GridBagLayout layout=new GridBagLayout();
     documents w1;
     request w2;
     deployment w3;
     reports w4;
    /**
     * Creates new form Panel2
     */
    public Panel2() {
        initComponents();
        
        w1=new documents();
        w2=new request();
        w3=new deployment();
        w4=new reports();
     
        
        panel1.setLayout(layout);
        GridBagConstraints c=new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        panel1.add(w1,c);
        c.gridx=0;
        c.gridy=0;
        panel1.add(w2,c);
        c.gridx=0;
        c.gridy=0;
        panel1.add(w3,c);
        c.gridx=0;
        c.gridy=0;
        panel1.add(w4,c);
        c.gridx=0;
        c.gridy=0;
        w1.setVisible(false);
        w2.setVisible(false);
        w3.setVisible(false);
        w4.setVisible(false);
    
  
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dep = new javax.swing.JButton();
        req = new javax.swing.JButton();
        report = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        docu = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setPreferredSize(new java.awt.Dimension(990, 440));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dep.setBackground(new java.awt.Color(255, 255, 255));
        dep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dep.setForeground(new java.awt.Color(0, 102, 0));
        dep.setText("DEPLOYMENT");
        dep.setToolTipText("");
        dep.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depActionPerformed(evt);
            }
        });
        add(dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 161, 29));

        req.setBackground(new java.awt.Color(255, 255, 255));
        req.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        req.setForeground(new java.awt.Color(0, 102, 0));
        req.setText("D.REQUEST");
        req.setToolTipText("");
        req.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        req.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqActionPerformed(evt);
            }
        });
        add(req, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 161, 29));

        report.setBackground(new java.awt.Color(255, 255, 255));
        report.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        report.setForeground(new java.awt.Color(0, 102, 0));
        report.setText("REPORTS");
        report.setToolTipText("");
        report.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 161, 29));

        panel1.setBackground(new java.awt.Color(153, 255, 153));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 950, 400));

        docu.setBackground(new java.awt.Color(255, 255, 255));
        docu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        docu.setForeground(new java.awt.Color(0, 102, 0));
        docu.setText("DOCUMENTS");
        docu.setToolTipText("");
        docu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        docu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docuActionPerformed(evt);
            }
        });
        add(docu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 160, 29));
    }// </editor-fold>//GEN-END:initComponents

    private void depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depActionPerformed
        // TODO add your handling code here:
        w1.setVisible(false);
        w2.setVisible(false);
        w3.setVisible(true);
        w4.setVisible(false);
    
    }//GEN-LAST:event_depActionPerformed

    private void reqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqActionPerformed
        // TODO add your handling code here:
        w1.setVisible(false);
        w2.setVisible(true);
        w3.setVisible(false);
        w4.setVisible(false);
     
    }//GEN-LAST:event_reqActionPerformed

    private void docuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docuActionPerformed
        // TODO add your handling code here:
        w1.setVisible(true);
        w2.setVisible(false);
        w3.setVisible(false);
        w4.setVisible(false);
  
    }//GEN-LAST:event_docuActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
        w1.setVisible(false);
        w2.setVisible(false);
        w3.setVisible(false);
        w4.setVisible(true);
  
    }//GEN-LAST:event_reportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dep;
    private javax.swing.JButton docu;
    private javax.swing.JPanel panel1;
    private javax.swing.JButton report;
    private javax.swing.JButton req;
    // End of variables declaration//GEN-END:variables
}
