/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facilityreservation;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author jimmelbermudez7
 */
public class facilityreservation extends javax.swing.JPanel {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;

    public facilityreservation() {
        initComponents();
                conn = databaseconn.ConnecrDb(); 
                Core1();
                facility();
                update1();
    }
public void Core1(){
    Thread clock= new Thread(){
    public void run(){
    for(;;){
    Calendar calen = GregorianCalendar.getInstance();
    int AM_PM = calen.get(Calendar.AM_PM);
    
     String tpattern = "hh:mm";
                    SimpleDateFormat tsdf = new SimpleDateFormat(tpattern);
                    
                    
    String [] days = new String [] {"","","","","","",""};
    String day_night = "";
            if (AM_PM==1)
            {day_night ="PM";}
            else
            {day_night = "AM";}
            
            
  //  time1.setText(hour+":"+mins+":"+secs); 



int mons = calen.get(Calendar.MONTH);
int day = calen.get(Calendar.DAY_OF_MONTH);
int yr = calen.get(Calendar.YEAR);
date.setText(days[calen.get(Calendar.DAY_OF_WEEK)-1]+" "+(mons+1)+"/"+day+"/"+yr);    
    try {
        sleep(1000);
    } catch (InterruptedException ex) {
        
    }
} } };

clock.start();
}
public void update1(){
  try{
           
           String sql;
            sql = "select VID,eventname,starttime,endtime,startday,endday,facilityname1,facilityid,approval from visitorreg";
           pst=conn.prepareStatement(sql);
           
           rs = pst.executeQuery();
           tbl2.setModel(DbUtils.resultSetToTableModel(rs));
          }
            catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
}
public void facility(){
     try{
           
           String sql;
            sql = "select FACILITYID,FACILITYNAME from facilities";
           pst=conn.prepareStatement(sql);
           
           rs = pst.executeQuery();
           tbl1.setModel(DbUtils.resultSetToTableModel(rs));
          }
            catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ok = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        facility = new javax.swing.JLabel();
        fid = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        avail = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        event = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        nop = new javax.swing.JTextField();
        st = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        et = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ed = new com.toedter.calendar.JDateChooser();
        sd = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ok.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, 40));

        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "RID", "LNAME", "FNAME", "MI", "GENDER", "PHONE/EMAIL", "DOR"
            }
        ));
        tbl2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbl2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl2);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 610, 190));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("SELECT FACILITY"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("FACILITY ID:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 80, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("FACILITY AVAILABILITY:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 140, 30));

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "RID", "LNAME", "FNAME", "MI", "GENDER", "PHONE/EMAIL", "DOR"
            }
        ));
        tbl1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbl1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 300, 170));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("FACILITY NAME:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 30, 90, 30));

        facility.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(facility, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 150, 30));

        fid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(fid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 150, 30));

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jRadioButton1.setText("USE");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 60, 30));
        jPanel1.add(avail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 100, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 320, 380));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 110, 30));
        jPanel3.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 160, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("EVENT NAME:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 80, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("PHONE/EMAIL:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 90, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("RID:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 30, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("DATE OF RESERVATION:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, 30));
        jPanel3.add(event, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 160, 30));

        date.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        date.setText("DATE OF RESERVATION:");
        jPanel3.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 160, 30));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 140));

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("NO. OF PARTICIPANTS:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 30));

        nop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nopKeyTyped(evt);
            }
        });
        jPanel4.add(nop, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 160, 30));
        jPanel4.add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 160, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("START TIME:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("END TIME:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 60, 30));
        jPanel4.add(et, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 160, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("END DATE:");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 60, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("START DATE:");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 80, 30));
        jPanel4.add(ed, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 160, 30));
        jPanel4.add(sd, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 100, 160, 30));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 300, 170));

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
try{
       String value1 = id.getText();
       String value2 = phone.getText();
       String value3 = event.getText();
       String value4 = date.getText();
       String value5 = nop.getText();
       String value6 = st.getText();
       String value7 = et.getText();
       String value8 = ((JTextField)sd.getDateEditor().getUiComponent()).getText();
       String value9 = ((JTextField)ed.getDateEditor().getUiComponent()).getText();
       String value10 = facility.getText();
       String value11 = fid.getText();
       String value12 = avail.getText();

       String sql = "update visitorreg set approval='APPROVE', phoneemail='"+value2+"', eventname='"+value3+"', datereservation='"+value4+"', noofparticipants='"+value5+"', starttime='"+value6+"', endtime='"+value7+"', startday='"+value8+"', endday='"+value9+"', facilityname1='"+value10+"',facilityid='"+value11+"',status='"+value12+"' where VID='"+value1+"'";
       pst=conn.prepareStatement(sql);
       pst.execute();
        id.setText("");           
        phone.setText("");
        event.setText("");
        date.setText(""); 
        nop.setText("");
        st.setText("");           
        et.setText("");
        facility.setText("");
        fid.setText(""); 
        
       JOptionPane.showMessageDialog(null, "Updated");
       }
        catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
       
        }
update1();
    }//GEN-LAST:event_okActionPerformed

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
     if(id.getTex­t().isEmpty()){

        id.setBackground(Color.yellow);
}else{

id.setBackground(Color.green);
}
        try {
            
            String sql= "select *from visitorreg where VID=?";
            
            pst=conn.prepareStatement(sql);
            pst.setString(1, id.getText());
            
            rs=pst.executeQuery();
            if(rs.next()){
            String add1=rs.getString("VID");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_idKeyReleased

    private void tbl1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbl1AncestorAdded
        try{
           
           String sql;
            sql = "select FACILITYID,FACILITYNAME from facilities ";
           pst=conn.prepareStatement(sql);
           
           rs = pst.executeQuery();
           tbl1.setModel(DbUtils.resultSetToTableModel(rs));
          }
            catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
        facility();
    }//GEN-LAST:event_tbl1AncestorAdded

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
         try{
        int row = tbl1.getSelectedRow();
        String Table_click=(tbl1.getModel().getValueAt(row, 0).toString());
        String sql ="select * from facilities where FACILITYID='"+Table_click+"'";
        pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
  if(rs.next()){
  
  String add1=rs.getString("FACILITYNAME");
  facility.setText(add1);
  String add2=rs.getString("FACILITYID");
  fid.setText(add2);
  String add3=rs.getString("AVAILABILITY");
  avail.setText(add3);
  
  }

        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);


        }
    }//GEN-LAST:event_tbl1MouseClicked

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)|| c==KeyEvent.VK_DELETE)){
        evt.consume();

}
    }//GEN-LAST:event_idKeyTyped

    private void nopKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nopKeyTyped
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)|| c==KeyEvent.VK_DELETE)){
        evt.consume();

}
    }//GEN-LAST:event_nopKeyTyped

    private void tbl2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbl2AncestorAdded
        // TODO add your handling code here:
        try{
           
           String sql;
            sql = "select VID,phoneemail,eventname,datereservation,noofparticipants,starttime,endtime,startday,endday,facilityname1,facilityid from visitorreg";
           pst=conn.prepareStatement(sql);
           
           rs = pst.executeQuery();
           tbl1.setModel(DbUtils.resultSetToTableModel(rs));
          }
            catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
        update1();
    }//GEN-LAST:event_tbl2AncestorAdded

    private void tbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
       String value1 = facility.getText();
       String value2 = fid.getText();
       String value3 = use;

       String sql = "update facilities set FACILITYNAME='"+value1+"', AVAILABILITY='"+value3+"' where FACILITYID='"+value2+"'";
       pst=conn.prepareStatement(sql);
       pst.execute();           
        avail.setText("");
        facility.setText("");
        fid.setText("");
        
       JOptionPane.showMessageDialog(null, "Updated");
       }
        catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
       
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
use="UNAVAILABLE";        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avail;
    private javax.swing.JLabel date;
    private com.toedter.calendar.JDateChooser ed;
    private javax.swing.JTextField et;
    private javax.swing.JTextField event;
    private javax.swing.JLabel facility;
    private javax.swing.JLabel fid;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nop;
    private javax.swing.JButton ok;
    private javax.swing.JTextField phone;
    private com.toedter.calendar.JDateChooser sd;
    private javax.swing.JTextField st;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    // End of variables declaration//GEN-END:variables
private String use;
private String app;
}
