/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package legalmanagement;

import java.awt.Color;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author jimmelbermudez7
 */
public class complaints extends javax.swing.JPanel {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null; 

    /**
     * Creates new form complaints
     */
    public complaints() {
        initComponents();
        conn = databaseconn.ConnecrDb();
        Update_table();
 Core1();   }
private void Update_table(){

        try{
           
           String sql;
            sql = "select * from complaints";
           pst=conn.prepareStatement(sql);
           
           rs = pst.executeQuery();
           tbl_complaints.setModel(DbUtils.resultSetToTableModel(rs));
          }
            catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }

}
public void Core1(){
    Thread clock= new Thread(){
    public void run(){
    for(;;){
    Calendar calen = GregorianCalendar.getInstance();
    int AM_PM = calen.get(Calendar.AM_PM);
                    
    String [] days = new String [] {"","","","","","",""};
    String day_night = "";
            if (AM_PM==1)
            {day_night ="PM";}
            else
            {day_night = "AM";}
            
  //  time1.setText(hour+":"+mins+":"+secs); 



int mons = calen.get(Calendar.MONTH);
int day = calen.get(Calendar.DAY_OF_MONTH);
int yr = calen.get(Calendar.YEAR);
date.setText(days[calen.get(Calendar.DAY_OF_WEEK)-1]+" "+(mons+1)+"/"+day+"/"+yr);    
    try {
        sleep(1000);
    } catch (InterruptedException ex) {
        
    }
} } };

clock.start();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_complaints = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txt_LNAME = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_FNAME = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_MI = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        txt_ADDRESS = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txt_WTC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_ROC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        wtcid = new javax.swing.JTextField();
        collection = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_complaints.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CID", "LNAME", "FNAME", "MI", "GENDER", "ADDRESS", "WTC", "ROC", "DOC", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_complaints.setColumnSelectionAllowed(true);
        tbl_complaints.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_complaints.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_complaintsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_complaints);
        if (tbl_complaints.getColumnModel().getColumnCount() > 0) {
            tbl_complaints.getColumnModel().getColumn(0).setResizable(false);
            tbl_complaints.getColumnModel().getColumn(1).setResizable(false);
            tbl_complaints.getColumnModel().getColumn(2).setResizable(false);
            tbl_complaints.getColumnModel().getColumn(3).setResizable(false);
            tbl_complaints.getColumnModel().getColumn(4).setResizable(false);
            tbl_complaints.getColumnModel().getColumn(5).setResizable(false);
            tbl_complaints.getColumnModel().getColumn(6).setResizable(false);
            tbl_complaints.getColumnModel().getColumn(7).setResizable(false);
            tbl_complaints.getColumnModel().getColumn(8).setResizable(false);
            tbl_complaints.getColumnModel().getColumn(9).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 950, 180));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("SEARCH:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 30));

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_save.setText("SAVE");
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
        });
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 100, 40));

        btn_edit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 90, 40));

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 240, 30));

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_LNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_LNAMEKeyTyped(evt);
            }
        });
        jPanel4.add(txt_LNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 200, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("LASTNAME:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        txt_FNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_FNAMEKeyTyped(evt);
            }
        });
        jPanel4.add(txt_FNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("FIRSTNAME:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 40, 70, 30));

        txt_MI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_MIKeyTyped(evt);
            }
        });
        jPanel4.add(txt_MI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("MIDDLENAME:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 70, 80, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("GENDER:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 30));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("MALE");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 90, 30));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("FEMALE");
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseClicked(evt);
            }
        });
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 100, 30));
        jPanel4.add(txt_ADDRESS, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 200, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("ADDRESS:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 30));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 170));

        jPanel5.setBackground(new java.awt.Color(153, 255, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_WTC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_WTCKeyTyped(evt);
            }
        });
        jPanel5.add(txt_WTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 160, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("WHO TO COMPLAIN:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("REASON OF COMPLAIN:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        txt_ROC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ROCKeyTyped(evt);
            }
        });
        jPanel5.add(txt_ROC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 370, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("IDNO:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 40, 30));

        wtcid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wtcidKeyTyped(evt);
            }
        });
        jPanel5.add(wtcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 60, 30));

        collection.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        collection.setText("COLLECTION");
        collection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectionActionPerformed(evt);
            }
        });
        jPanel5.add(collection, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 100, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("TIME/DATE OF COMPLAIN:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 30));

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setText("DATE");
        jPanel5.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 350, 30));

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("ADMINISTRATIVE CASE");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("TYPE OF CASE:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 40));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("CRIMINAL CASE");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 130, 40));

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 590, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked
        // TODO add your handling code here:   
        try{
            
        String sql = "insert into complaints (LNAME,FNAME,MI,GENDER,ADDRESS,WTC,WTCID,ROC,DOC,TOC)values(?,?,?,?,?,?,?,?,?,?)";
            

    pst=conn.prepareStatement(sql);
                      
    pst.setString(1, txt_LNAME.getText());            
    pst.setString(2, txt_FNAME.getText());
    pst.setString(3, txt_MI.getText());           
    pst.setString(4, txt_GENDER);            
    pst.setString(5, txt_ADDRESS.getText());
    pst.setString(6, txt_WTC.getText());
    pst.setString(7, wtcid.getText());          
    pst.setString(8, txt_ROC.getText());
    pst.setString(9, date.getText());    
    pst.setString(10, TYPE);
    
    pst.execute();            
    txt_LNAME.setText("");           
    txt_FNAME.setText("");
    txt_MI.setText("");
    txt_ADDRESS.setText(""); 
    txt_WTC.setText("");           
    wtcid.setText(""); 
    txt_ROC.setText("");
    
      JOptionPane.showMessageDialog(null, "Saved");
      
      }
        catch(Exception e){
      JOptionPane.showMessageDialog(null, e);        
        }
         Update_table();  
    }//GEN-LAST:event_btn_saveMouseClicked

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
  

    }//GEN-LAST:event_btn_saveActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
      
 
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        // TODO add your handling code here:
        txt_GENDER="M";
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseClicked
        // TODO add your handling code here:
        txt_GENDER="F";
    }//GEN-LAST:event_jRadioButton3MouseClicked

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_complaints.getSelectedRow();
     
        DefaultTableModel model = (DefaultTableModel)tbl_complaints.getModel();
        txt_LNAME.setText(model.getValueAt(selectedRow, 1).toString());
        txt_FNAME.setText(model.getValueAt(selectedRow, 2).toString());
        txt_MI.setText(model.getValueAt(selectedRow, 3).toString());
 
        txt_ADDRESS.setText(model.getValueAt(selectedRow, 5).toString());
        txt_WTC.setText(model.getValueAt(selectedRow, 6).toString());
        txt_ROC.setText(model.getValueAt(selectedRow, 7).toString());
       
        
        
    }//GEN-LAST:event_btn_editActionPerformed

    private void tbl_complaintsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_complaintsMouseClicked

    }//GEN-LAST:event_tbl_complaintsMouseClicked

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        if(txt_search.getTex­t().isEmpty()){

        txt_search.setBackground(Color.yellow);
}else{

txt_search.setBackground(Color.green);
}
        try {
            
            String sql= "select *from complaints where CID=?";
            
            pst=conn.prepareStatement(sql);
            pst.setString(1, txt_search.getText());
            
            rs=pst.executeQuery();
            if(rs.next()){
            String add1=rs.getString("CID");
            String add2=rs.getString("LNAME");
            txt_LNAME.setText(add2);
            String add3=rs.getString("FNAME");
            txt_FNAME.setText(add3);
            String add4=rs.getString("MI");
            txt_MI.setText(add4);
            
            String add6=rs.getString("ADDRESS");
            txt_ADDRESS.setText(add6);
            String add7=rs.getString("WTC");
            txt_WTC.setText(add7);
            String add8=rs.getString("ROC");
            txt_ROC.setText(add8);
            
            
            
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_searchActionPerformed

    private void collectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectionActionPerformed
        // TODO add your handling code here:
      employee1 newform = new employee1();                
      newform.setVisible(true);
    }//GEN-LAST:event_collectionActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        TYPE="ADMINISTRATIVECASE";
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        TYPE="CRIMINALCASE";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void txt_LNAMEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_LNAMEKeyTyped
char c=evt.getKeyChar();
     if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
           
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LNAMEKeyTyped

    private void txt_FNAMEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FNAMEKeyTyped
char c=evt.getKeyChar();
     if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
           
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FNAMEKeyTyped

    private void txt_MIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MIKeyTyped
char c=evt.getKeyChar();
     if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
           
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MIKeyTyped

    private void txt_WTCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_WTCKeyTyped
char c=evt.getKeyChar();
     if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
           
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_WTCKeyTyped

    private void txt_ROCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ROCKeyTyped
char c=evt.getKeyChar();
     if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
           
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ROCKeyTyped

    private void wtcidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wtcidKeyTyped
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)|| c==KeyEvent.VK_DELETE)){
        evt.consume();

}
    }//GEN-LAST:event_wtcidKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_save;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton collection;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_complaints;
    private javax.swing.JTextField txt_ADDRESS;
    private javax.swing.JTextField txt_FNAME;
    private javax.swing.JTextField txt_LNAME;
    private javax.swing.JTextField txt_MI;
    private javax.swing.JTextField txt_ROC;
    private javax.swing.JTextField txt_WTC;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField wtcid;
    // End of variables declaration//GEN-END:variables
private String txt_GENDER;
private String txt_STATUS;
private String TYPE;
}
