/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package legalmanagement;

import java.awt.Desktop;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author jimmelbermudez7
 */
public class documents extends javax.swing.JPanel {

    /**
     * Creates new form documents
     */
    public documents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adddocu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tree2 = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        tree1 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        open = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtree3 = new javax.swing.JTree();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adddocu.setBackground(new java.awt.Color(255, 255, 255));
        adddocu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adddocu.setForeground(new java.awt.Color(0, 102, 0));
        adddocu.setText("ADD DOCUMENT");
        adddocu.setToolTipText("");
        adddocu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        adddocu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddocuActionPerformed(evt);
            }
        });
        add(adddocu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 40));

        tree2.setModel(new FileSystemModel(new File("C:\\Users\\jimmelbermudez7\\Desktop\\permits")));
        tree2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tree2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tree2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 330, 240));

        tree1.setModel(new FileSystemModel(new File("C:\\Users\\jimmelbermudez7\\Desktop\\contracts")));
        tree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tree1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tree1);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 320, 240));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("PERMITS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("TERMS & POLICY");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, 30));

        open.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        open.setText("OPEN FILE");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        add(open, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 90, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("CONTRACTS");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, 30));

        jtree3.setModel(new FileSystemModel(new File("C:\\Users\\jimmelbermudez7\\Desktop\\terms and policy")));
        jtree3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtree3MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtree3);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 300, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void adddocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddocuActionPerformed
        // TODO add your handling code here:
   try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Users\\jimmelbermudez7\\Desktop\\Word 2016");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_adddocuActionPerformed

    private void tree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tree1MouseClicked
        Jtreevar=tree1.getSelectionPath().toString().replaceAll("[\\[\\]]", "").replace(", ", "\\");
    }//GEN-LAST:event_tree1MouseClicked

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
     try{
         File Selection=new File(Jtreevar);
         if(Selection.exists()){
         if(Desktop.isDesktopSupported()){
             Desktop.getDesktop().open(Selection);             
         }else{
             JOptionPane.showMessageDialog(null, "cant open file");
         }             
         }else{
         JOptionPane.showMessageDialog(null, "cant open file");
         
         }
         
     }catch(Exception ex) {
         JOptionPane.showMessageDialog(null, "cant open file");
     }
    }//GEN-LAST:event_openActionPerformed

    private void tree2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tree2MouseClicked
        Jtreevar=tree2.getSelectionPath().toString().replaceAll("[\\[\\]]", "").replace(", ", "\\");
    }//GEN-LAST:event_tree2MouseClicked

    private void jtree3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtree3MouseClicked
        Jtreevar=jtree3.getSelectionPath().toString().replaceAll("[\\[\\]]", "").replace(", ", "\\");        // TODO add your handling code here:
    }//GEN-LAST:event_jtree3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adddocu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jtree3;
    private javax.swing.JButton open;
    private javax.swing.JTree tree1;
    private javax.swing.JTree tree2;
    // End of variables declaration//GEN-END:variables
String Jtreevar;

}
