/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package legalmanagement;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author jimmelbermudez7
 */
public class legalcases extends javax.swing.JPanel {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;

 GridBagLayout layout=new GridBagLayout();
     admin b1;
     crim b2;

    public legalcases() {
        initComponents();
        conn = databaseconn.ConnecrDb();
        b1=new admin();
        b2=new crim();   
        
        panel.setLayout(layout);
        GridBagConstraints c=new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        panel.add(b1,c);
        c.gridx=0;
        c.gridy=0;
        panel.add(b2,c);
        b1.setVisible(true);
        b2.setVisible(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crim = new javax.swing.JButton();
        admin = new javax.swing.JButton();
        panel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crim.setBackground(new java.awt.Color(255, 255, 255));
        crim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        crim.setForeground(new java.awt.Color(0, 102, 0));
        crim.setText("CRIMINAL CASES");
        crim.setToolTipText("");
        crim.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        crim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crimActionPerformed(evt);
            }
        });
        add(crim, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 210, 40));

        admin.setBackground(new java.awt.Color(255, 255, 255));
        admin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        admin.setForeground(new java.awt.Color(0, 102, 0));
        admin.setText("ADMINISTRATIVE CASES");
        admin.setToolTipText("");
        admin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 190, 40));

        panel.setBackground(new java.awt.Color(153, 255, 153));
        add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 950, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void crimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crimActionPerformed
        // TODO add your handling code here:
        b1.setVisible(false);
        b2.setVisible(true);
    }//GEN-LAST:event_crimActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
        b1.setVisible(true);
        b2.setVisible(false);

    }//GEN-LAST:event_adminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JButton crim;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables


private String done;
}
