/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package legalmanagement;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author jimmelbermudez7
 */
public class legaldocument extends javax.swing.JPanel {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;
    
    public legaldocument() {
        initComponents();
        conn = databaseconn.ConnecrDb();
        Core1(); 
    }
    public void Core1(){
    Thread clock= new Thread(){
    public void run(){
    for(;;){
    Calendar calen = GregorianCalendar.getInstance();
    int AM_PM = calen.get(Calendar.AM_PM);

    String [] days = new String [] {"","","","","","",""};
    String day_night = "";
            if (AM_PM==1)
            {day_night ="PM";}
            else
            {day_night = "AM";}
            
  //  time1.setText(hour+":"+mins+":"+secs); 


    
int mons = calen.get(Calendar.MONTH);
int day = calen.get(Calendar.DAY_OF_MONTH);
int yr = calen.get(Calendar.YEAR);
date.setText(days[calen.get(Calendar.DAY_OF_WEEK)-1]+" "+(mons+1)+"/"+day+"/"+yr);    
    try {
        sleep(1000);
    } catch (InterruptedException ex) {
        
    }

} } };

clock.start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_doc = new javax.swing.JTable();
        btn_edit = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setPreferredSize(new java.awt.Dimension(790, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Req.ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 40));

        tbl_doc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DID", "KIND OF DOC.", "DATE OF SUB.", "Title 4", "Title 5", "Title 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_doc.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbl_docAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbl_doc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_docMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_doc);
        if (tbl_doc.getColumnModel().getColumnCount() > 0) {
            tbl_doc.getColumnModel().getColumn(0).setResizable(false);
            tbl_doc.getColumnModel().getColumn(1).setResizable(false);
            tbl_doc.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 950, 260));

        btn_edit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 90, 40));

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 90, 40));

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setText("DATE");
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 140, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("DATE OF APPROVAL:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("APPROVAL:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 40));

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 130, 40));

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton1.setText("APPROVE");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 80, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
   int selectedRow = tbl_doc.getSelectedRow();
     
        DefaultTableModel model = (DefaultTableModel)tbl_doc.getModel();
        id.setText(model.getValueAt(selectedRow, 0).toString());
        date.setText(model.getValueAt(selectedRow, 5).toString());

      
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
  try{
       String value1 = id.getText();
       String value2 = app;
       String value3 = date.getText();

       String sql="update reqdocument set approval='"+value2+"' , approvaldate='"+value3+"' where ReqID='"+value1+"'";
       pst=conn.prepareStatement(sql);
       pst.execute();
       JOptionPane.showMessageDialog(null, "Updated");
       }
        catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
        }
  Update_table();
                           
    }//GEN-LAST:event_btn_saveActionPerformed

    private void tbl_docMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_docMouseClicked

    }//GEN-LAST:event_tbl_docMouseClicked

    private void tbl_docAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbl_docAncestorAdded
        // TODO add your handling code here:
        Update_table();
    }//GEN-LAST:event_tbl_docAncestorAdded

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
        app="APPROVE";
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
        // TODO add your handling code here:
           try {
            
            String sql= "select *from reqdocument where ReqID=?";
            
            pst=conn.prepareStatement(sql);
            pst.setString(1, id.getText());
            
            rs=pst.executeQuery();
            if(rs.next()){
            String add1=rs.getString("ReqID");
            id.setText(add1);
          
            

            
            
            
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_idKeyReleased

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
  char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)|| c==KeyEvent.VK_DELETE)){
        evt.consume();

}        // TODO add your handling code here:
    }//GEN-LAST:event_idKeyTyped
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel date;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_doc;
    // End of variables declaration//GEN-END:variables
public void Update_table(){
try{
           
           String sql;
            sql = "select ReqID,kindofdocu,reqdate,documentreq,approval,approvaldate from reqdocument";
           pst=conn.prepareStatement(sql);
           
           rs = pst.executeQuery();
           tbl_doc.setModel(DbUtils.resultSetToTableModel(rs));
          }
            catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
}
private String app;
}



