/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pointofsale;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author jimmelbermudez7
 */
public class bankdeposit extends javax.swing.JPanel {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;
/**
     * Creates new form 
     */
    public bankdeposit() {
        initComponents();

     conn = databaseconn.ConnecrDb();
     Update_table();
    }
 private void Update_table(){

        try{
           
           String sql;
            sql = "select depositno,fname,lname,middlename,address,accountnumber,amount,currency,month,date,year from pointofsale";
           pst=conn.prepareStatement(sql);
           
           rs = pst.executeQuery();
           tbl.setModel(DbUtils.resultSetToTableModel(rs));
          }
            catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        acc = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        OPEN = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        attach_image = new javax.swing.JButton();
        path = new javax.swing.JTextField();
        comboyear = new javax.swing.JComboBox<>();
        combomonth = new javax.swing.JComboBox<>();
        comboday = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        address = new javax.swing.JTextField();
        mi = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("ACCOUNT NUMBER:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("AMOUNT:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, 30));
        add(acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 240, 30));
        add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 240, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("DATE:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 40, 30));

        tbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 950, 180));

        OPEN.setText("VIEW");
        OPEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPENActionPerformed(evt);
            }
        });
        add(OPEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 60, 30));

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("U.S DOLLAR");
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseClicked(evt);
            }
        });
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 110, 30));

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("PHILIPPINE PESO");
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton4MouseClicked(evt);
            }
        });
        add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("CURRENCY:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 70, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 70, 30));

        attach_image.setText("ATTACH BASIS");
        attach_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attach_imageActionPerformed(evt);
            }
        });
        add(attach_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, 30));
        add(path, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 300, 30));

        comboyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
        comboyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboyearActionPerformed(evt);
            }
        });
        add(comboyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 70, 30));

        combomonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));
        combomonth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combomonthMouseClicked(evt);
            }
        });
        combomonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combomonthActionPerformed(evt);
            }
        });
        add(combomonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 60, 30));

        comboday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        add(comboday, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 50, 30));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 220, 30));
        jPanel3.add(mi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 220, 30));

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        jPanel3.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 220, 30));
        jPanel3.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 220, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("FIRST NAME:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("LAST NAME:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 70, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("MIDDLE NAME:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("ADDRESS:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 60, 30));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 370, 140));

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 230, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void OPENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPENActionPerformed
   RECEIPTS newform = new RECEIPTS();                
      newform.setVisible(true);    
    }//GEN-LAST:event_OPENActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try{
            
        String sql = "insert into pointofsale (fname,lname,middlename,address,accountnumber,amount,currency,month,date,year,basispic)values(?,?,?,?,?,?,?,?,?,?,?)";
            

    pst=conn.prepareStatement(sql);
                      
           
    pst.setString(1, fname.getText());
    pst.setString(2, lname.getText());           
    pst.setString(3, mi.getText());            
    pst.setString(4, address.getText());
    pst.setString(5, acc.getText());
    pst.setString(6, amount.getText());          
    pst.setString(7, currency);
    String value=combomonth.getSelectedItem().toString();
    pst.setString(8,value);
    String value1=comboday.getSelectedItem().toString();
    pst.setString(9,value1);
    String value2=comboyear.getSelectedItem().toString();
    pst.setString(10,value2);
    pst.setBytes(11, person_image);
    pst.execute();            
           
    fname.setText("");
    lname.setText("");
    mi.setText("");
    address.setText("");       
    acc.setText(""); 
    amount.setText("");
    path.setText("");
    
      JOptionPane.showMessageDialog(null, "Saved");
      
      }
        catch(Exception e){
      JOptionPane.showMessageDialog(null, e);        
        }
        Update_table();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton4MouseClicked
currency="PESO";        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4MouseClicked

    private void jRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseClicked
currency="DOLLAR";        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3MouseClicked

    private void tblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblAncestorAdded
Update_table();        // TODO add your handling code here:
    }//GEN-LAST:event_tblAncestorAdded

    private void attach_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attach_imageActionPerformed
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        path.setText(filename);

        try{
            File image =new File (filename);
            FileInputStream fis= new FileInputStream(image);

            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for(int readNum; (readNum=fis.read(buf))!=-1; ){
                bos.write(buf,0,readNum);

            }
            person_image=bos.toByteArray();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);;
        }

    }//GEN-LAST:event_attach_imageActionPerformed

    private void comboyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboyearActionPerformed

    private void combomonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combomonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combomonthActionPerformed

    private void combomonthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combomonthMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_combomonthMouseClicked

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OPEN;
    private javax.swing.JTextField acc;
    private javax.swing.JTextField address;
    private javax.swing.JTextField amount;
    private javax.swing.JButton attach_image;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> comboday;
    private javax.swing.JComboBox<String> combomonth;
    private javax.swing.JComboBox<String> comboyear;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mi;
    private javax.swing.JTextField path;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

private String currency;
private ImageIcon format =null;
String filename=null;
int s=0;
byte[] person_image=null;
}

